project:
  type: book
  execute-dir: "project"
  output-dir: ./_site
  preview:
    port: 4200
    browser: false
  resources:
  - functions/

book:
  title: "Biostatistika"
  subtitle: "BISB211203 - TA 2025/2026"
  #downloads: pdf
  #cover-image: cover.webp
  author:
    - Matin Nuhamunada, M.Sc., Ph.D.
    - Dr. Wiko Arif Wibowo, S.Si. 
    - Dr. Aprilia Sufi Subiastuti, S.Si.
    - Nur Indah Septriani, M.Sc., Ph.D.
    -	Dr. Siti Nurbaiti, S.Si.
    -	Dr. Eng. Atikah Fitria Muharromah, M.Eng.
    - Dr. Eng. Thoriq Teja Samudra, M.Sc.
    - Aries Bagus Sasongko, S.Si., M.Biotech.
    - Sidiq Permana Putra, S.Si., M.Sc.
    - Rahadian Yudo Hartantyo, M.Sc., Ph.D.
  date: "3/4/2026"
  chapters:
    - index.qmd
  page-footer:
    left: |
      ::: {.columns}

      ::: {.column width="100%"}
      ![](/assets/images/faculty_biology_ugm.png){fig-align="left" style="max-width: 100%; margin-right: 10px; max-height: 75px;"}
      :::

      :::
      Copyright 2026, Universitas Gadjah Mada
    right:
      - icon: github
        href: https://github.com/lab-biotek-bio-ugm/BISB211203

highlight-style: pygments

bibliography: references.bib

profile:
  default: id
  group:
    - [def,en,id]

format:
  html:
    css: styles.css
    smooth-scroll: true
    link-external-icon: true
    toc-location: left
    toc-expand: false
    theme:
      - cosmo
      - brand
    mermaid:
      theme: forest
    code-copy: true
    comments:
      hypothesis: true

execute:
  freeze: true
  echo: true
